practice1/config/routes.rb
Rails.application.routes.draw do
resource :lists

  get 'say/hello'

  get 'say/goodbye'

  get 'say/about'

  get 'files' => "files#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

practice1/app/controllers/files_controller.rb
class FilesController < ApplicationController


  def index
    if params[:next]
      path = params[:next] + "/*"
      @files = Dir[path]

      @parent = path.split("/")[0..-3].join("/")
    else
      @files = Dir["*"]
  end
end

practice1/app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @date = "#{@time.day}/#{@time.month}/#{@time.year}"
    @year = @time.year
  end

  def goodbye
    @time = Time.now
    @hour = @time.hour
  end

  def about
    
  end

end

practice1/app/helpers/files_helper.rb
module FilesHelper
end

practice1/app/helpers/say_helper.rb
module SayHelper
end

practice1/app/views/files/index.html.erb
<h1><%= link_to "File" ,files_path %></h1>


<ul class="files">
 <li class="file"><%= link_to ".." , file_path(next: @parent) %></li>
 <% @files.each  do |file|  %>
  <li class="file"><%=link_to file, files_path(next: file) %></li>
 <%end%>
</ul>

practice1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Practice1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

practice1/app/views/say/about.html.erb
<h1>Rails Portal</h1>
<p>Welcome</p>


<a href="/say/hello">Back</a>

practice1/app/views/say/goodbye.html.erb
<h1>Say Goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>

<p>(c) <%=@hour%></p>
<a href="/say/hello">Back</a>

</br>
<a><%= link_to "About" , "/say/about"%></a>

practice1/app/views/say/hello.html.erb
<h1>Hello from Rails</h1>
<p>Time is <%=@date%></p>
<p>(c) <%=@year%></p>

<a href="/say/goodbye">GoodBye</a></br>

<a href="/say/about">About</a>