assignment/Resto2/config/routes.rb
Rails.application.routes.draw do
  get 'cart' => 'carts#show'

  resources :photos

  root "home#index"
  
  get 'home/about' => "home#about"
  get 'contact' => "contact#index"
  get 'menu' => "menu#index"
  resources :carts
  resources :line_items
  
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

assignment/Resto2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  

end

assignment/Resto2/app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items , dependent: :destroy

  def items_count
    line_items.count
  end

end

assignment/Resto2/app/models/item.rb
class Item < ApplicationRecord
  belongs_to :section
end

assignment/Resto2/app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

assignment/Resto2/app/models/section.rb
class Section < ApplicationRecord
  validates :name, presence: true
  has_many :items, dependent: :destroy
end

assignment/Resto2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_cart

  def current_cart
    @cart = Cart.find(session[:cart_id])  
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create!
    session[:cart_id] = @cart.id
  end

end

assignment/Resto2/app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def index
  end

  def show
    
  end

end

assignment/Resto2/app/controllers/contact_controller.rb
class ContactController < ApplicationController
 
  def index
  end
  
end

assignment/Resto2/app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
end

assignment/Resto2/app/controllers/items_controller.rb
class ItemsController < ApplicationController
end

assignment/Resto2/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  def create
    @lineitem = LineItem.new(line_item_params)
    if @lineitem.save
      redirect_to cart_path
    else
      redirect_to :back 
    end
  end

  def line_item_params
    params.require(:line_item).permit(:item_id, :cart_id, :quantity)
  end

end

assignment/Resto2/app/controllers/menu_controller.rb
class MenuController < ApplicationController
  def index
    @sections = Section.all
    if params[:section]
      @section = Section.find_by(name:params[:section])
      @items = @section.items
    end
  end
end

assignment/Resto2/app/helpers/application_helper.rb
module ApplicationHelper
end

assignment/Resto2/app/helpers/cart_helper.rb
module CartHelper
end

assignment/Resto2/app/helpers/contact_helper.rb
module ContactHelper
end

assignment/Resto2/app/helpers/home_helper.rb
module HomeHelper
end

assignment/Resto2/app/helpers/items_helper.rb
module ItemsHelper
end

assignment/Resto2/app/helpers/line_items_helper.rb
module LineItemsHelper
end

assignment/Resto2/app/helpers/menu_helper.rb
module MenuHelper
end

assignment/Resto2/app/views/carts/index.html.erb
<h1>You'r options</h1>

<nav>
    <div class="nav-wrapper teal lighten-2">
      <a href="#" class="brand-logo"><h3 class="besedwi">Rest2</h3></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down ">
        <li><a><%= link_to "Menu" , menu_path %></a></li>

        <li><a href="/home/about">About us</a></li>
        <li><a><%= link_to "Find Us" , contact_path %></a></li>
      </ul>
    </div>
  </nav>

<!--
<table>
        <thead>
          <tr>
              <th>Name</th>
              <th>Item Name</th>
              <th>Item Price</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td>Alvin</td>
            <td>Eclair</td>
            <td>$0.87</td>
          </tr>
          <tr>
            <td>Alan</td>
            <td>Jellybean</td>
            <td>$3.76</td>
          </tr>
          <tr>
            <td>Jonathan</td>
            <td>Lollipop</td>
            <td>$7.00</td>
          </tr>
        </tbody>
      </table>
      
      -->

assignment/Resto2/app/views/carts/show.html.erb
<nav>
  <div class="nav-wrapper teal lighten-2">
    <a href="#" class="brand-logo"><h3 class="besedwi">Rest2</h3></a>
    <ul id="nav-mobile" class="right hide-on-med-and-down ">
      <li><a><%= link_to "Menu" , menu_path %></a></li>
      <li><a href="/home/about">About us</a></li>
      <li><a><%= link_to "Find Us" , contact_path %></a></li>
    </ul>
  </div>
</nav>

<%= debug current_cart.id %>
<table>
        <thead>
          <tr>
              <th></th>
              <th></th>
              <th></th>
          </tr>
        </thead>

        <tbody>
        <% current_cart.line_items.each do |line| %>
        <tr>
            <td><%= line.item.name %></td>
            <td><%= line.quantity %></td>
            <td><%= line.item.price %></td>
        </tr>
       <% end %>   
  </tbody>
</table>

assignment/Resto2/app/views/home/about.html.erb
<nav>
    <div class="nav-wrapper teal lighten-2">
      <a href="#" class="brand-logo"><h3 class="besedwi">Rest2</h3></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down ">
        <li><a><%= link_to "Home" , root_path %></a></li>

        <li><a><%= link_to "Menu" , menu_path %></a></li>
        <li><a><%= link_to "Find us" , contact_path %></a></li>
      </ul>
    </div>
  </nav>

  <div class="row upTo">
  <div class="col s4 push-s2 card-panel about">
    <h3>About us..</h3>
    <p class="">I am a very simple card. I am good at containing small bits of information</p>
 </div>
</div>


<div class='video-container under'>
  <%= video_tag "The_Cucumber.mp4", autoplay: :autoplay, loop: :loop, mute: :mute, class: "video" %>
</div>

assignment/Resto2/app/views/home/index.html.erb
<nav>
    <div class="nav-wrapper teal lighten-2">
      <a href="#" class="brand-logo"><h3 class="besedwi">Rest2</h3></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down ">
        <li><a><%= link_to "Menu" , menu_path %></a></li>

        <li><a href="/home/about">About us</a></li>
        <li><a><%= link_to "Find Us" , contact_path %></a></li>
      </ul>
    </div>
  </nav>


<div class='video-container'>
  <%= video_tag "avo-egg.mp4", autoplay: :autoplay, loop: :loop, mute: :mute, class: "video" %>
</div>


<div class="row text-center">
<h2>Day's Sales</h2>

<div class="col s3 inline" id="menu">
    <h2 class="header"></h3>
    <div class="card">
      <div class="card-image">
        <img src="<%= image_path 'Dinner1.jpg' %>">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p>I am a very simple card. I am good at containing small bits of information.</p>
        </div>
        <div class="card-action">
          <a><%= link_to "Take a look" ,menu_path %></a>
        </div>
      </div>
    </div>
  </div>

  <div class="col s3 inline" id="menu">
    <h2 class="header"></h2>
    <div class="card">
      <div class="card-image">
        <img src="<%= image_path 'Lunch5.jpg' %>">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p>I am a very simple card. I am good at containing small bits of information.</p>
        </div>
        <div class="card-action">
          <a><%= link_to "Take a look" ,menu_path %></a>
        </div>
      </div>
    </div>
  </div>

  <div class="col s3 inline" id="menu">
    <h2 class="header"></h2>
    <div class="card">
      <div class="card-image">
        <img src="<%= image_path 'Breakfast1.jpg' %>">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p>I am a very simple card. I am good at containing small bits of information.</p>
        </div>
        <div class="card-action">
          <a><%= link_to "Take a look" ,menu_path %></a>
        </div>
      </div>
    </div>
  </div>

  <div class="col s3 inline" id="menu">
    <h2 class="header"></h2>
    <div class="card">
      <div class="card-image">
        <img src="<%= image_path 'Dessert1.jpg' %>">
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p>I am a very simple card. I am good at containing small bits of information.</p>
        </div>
        <div class="card-action">
          <a><%= link_to "Take a look" ,menu_path %></a>
        </div>
      </div>
    </div>
  </div>

</div>




<footer class="page-footer teal lighten-2">
   <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Follow us on</h5>
          <p class="grey-text text-lighten-4"></p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text"></h5>
        <div class"row">
          <ul>
            <i class="material-icons">access_time</i>
            <i class="material-icons">android</i>
            <i class="material-icons">wifi</i>
            <i class="material-icons">accessible</i>
          </ul>
          </div>
      </div>
    </div>
   </div>

  <div class="footer-copyright">
    <div class="container">
      © 2017 Copyright Text
      <a class="grey-text text-lighten-4 right" href="#!">Work with us</a>
    </div>
  </div>
</footer>

assignment/Resto2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Resto2</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.1/css/materialize.min.css">  
     <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Sedgwick+Ave" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Archivo" rel="stylesheet">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

assignment/Resto2/app/views/line_items/create.html.erb
<h1>LineItems#create</h1>
<p>Find me in app/views/line_items/create.html.erb</p>

assignment/Resto2/app/views/menu/index.html.erb
<div class="row">
<nav class="nav-extended teal lighten-2">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo"><h4 class="besedwi">Rest2</h4></a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a><%= link_to "Home" , root_path %></a></li>
        <li>
          <%= link_to cart_path do  %>
            <i class="material-icons">add_shopping_cart</i></a>
            <%=current_cart.items_count %>
          <% end %>
        </li>
        <li><a><%= link_to "Find us" , contact_path %></a></li>
        <li><a href="/home/about">About us</a></li>
      </ul>
    </div>

    <div class="nav-content">
      <ul class="tabs tabs-transparent">
        <% @sections.each do |section| %>
        <li class="tab">
         <%= link_to(section.name , menu_path(section:section.name),
              class:"#{'active' if params[:section] == section.name}") %>
        </li>
         <% end %>
      </ul>
    </div>
  </nav>
</div>


<div class="row text-center">
<% if @section  %>
<h2><%= @section.name %></h2>
 <% @items.each do |item|%>
<div class="col s3 inline" id="menu">
    <div class="card">
    <h4 class="header"><%= item.name %></h4>
    <div class="card-image">
       <%= image_tag(item.image_url) %>
      </div>
      <div class="card-stacked">
        <div class="card-content">
          <p><%= item.description %></p>
          <p><strong><%= number_to_currency(item.price) %></strong></p>
        </div>
        <%= form_for LineItem.new do |f|%>
          <%= f.hidden_field :item_id, value: item.id %>
          <%= f.hidden_field :cart_id, value: current_cart.id %>
          <%= f.number_field :quantity, value: 1 %>
          <%= f.submit 'add to cart', class: 'btn' %> 
        <%end%>
      </div>
  </div>
</div>  
<% end %>

<% end %>
</div>
  